# Generated by Django 5.2.12 on 2026-04-02 19:38

from django.db import migrations


def create_profiles(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    UserProfile = apps.get_model('account', 'UserProfile')
    for account in Account.objects.all():
        UserProfile.objects.get_or_create(user=account)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, reverse_noop),
    ]
