"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'www.nyasablog.com', 'nyasablog.com']


# Application definition

INSTALLED_APPS = [

    # My apps
    'personal',
    'account',
    'blog',
    'django_ckeditor_5',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'storages',
    'rest_framework',
    'rest_framework.authtoken',
    'django_htmx',
    'anymail',
]

AUTH_USER_MODEL = 'account.Account'

AUTHENTICATION_BACKENDS = (
    'account.backends.CaseInsensitiveModelBackend',
)
    
    
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_VERSION': '1',
    'ALLOWED_VERSIONS': ['1', '2'],
}
    
    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

TEMP = os.path.join(BASE_DIR, 'temp')
FILE_UPLOAD_PERMISSIONS = 0o644

SUPPORT_EMAIL = config('SUPPORT_EMAIL', default='hello@nyasablog.com')

if DEBUG:
    # Local development: use filesystem for static/media
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: DigitalOcean Spaces (S3-compatible)
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = config('AWS_LOCATION')
    AWS_DEFAULT_ACL = 'public-read'
    STATIC_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
    }
    # Default backend is Postmark via Anymail. Override via env (e.g.
    # EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend) for emergency
    # rollback without redeploying — the SMTP settings below stay populated
    # from .env so the SMTP backend has what it needs if reactivated.
    EMAIL_BACKEND = config(
        'EMAIL_BACKEND',
        default='anymail.backends.postmark.EmailBackend',
    )
    ANYMAIL = {
        'POSTMARK_SERVER_TOKEN': config('POSTMARK_SERVER_TOKEN', default=''),
    }
    # Fail loud at startup if Postmark is the active backend but the token is
    # missing — otherwise Anymail sends with a blank token and Postmark returns
    # 401 only on the first user-triggered send, which is a much worse failure
    # mode (live user-facing 500 vs. deploy-time alarm). Empty default is kept
    # so the SMTP rollback path doesn't require the token to be set.
    if EMAIL_BACKEND == 'anymail.backends.postmark.EmailBackend' and not ANYMAIL['POSTMARK_SERVER_TOKEN']:
        raise ImproperlyConfigured(
            'POSTMARK_SERVER_TOKEN must be set when EMAIL_BACKEND is the Postmark backend.'
        )
    EMAIL_HOST = config('EMAIL_HOST', default='')
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    # Fail fast (10s) so view exception handlers run before gunicorn's 30s
    # worker timeout fires. Without this, hanging connects → SIGABRT →
    # 500 with no chance to release the resend cooldown cache.
    EMAIL_TIMEOUT = 10

    # HTTPS / cookie security. Nginx terminates TLS and forwards X-Forwarded-Proto,
    # so request.is_secure() and the SSL redirect both rely on SECURE_PROXY_SSL_HEADER.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='NyasaBlog <hello@nyasablog.com>',
)

# Verification-email link domain. Sourced from settings.ini, not request.get_host(),
# so a forged Host header cannot redirect verification links to an attacker domain.
SITE_DOMAIN = config('SITE_DOMAIN', default='localhost:8000')
SITE_PROTOCOL = config('SITE_PROTOCOL', default='http')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'bulletedList', 'numberedList', '|',
            'blockQuote', 'codeBlock', '|',
            'link', 'imageUpload', '|',
            'undo', 'redo',
        ],
        'height': '400px',
        'width': '100%',
    },
}
CK_EDITOR_5_UPLOAD_FILE_VIEW_NAME = "ck_editor_5_upload_file"

