# Generated by Django 5.2.12 on 2026-04-02 19:35

from django.db import migrations
from django.utils.text import slugify


CATEGORIES = [
    ('Culture', 'Malawian traditions, arts, and heritage'),
    ('Entertainment', 'Music, film, events, and pop culture'),
    ('Entrepreneurship', 'Business, startups, and innovation'),
    ('Tourism', 'Travel, destinations, and hospitality'),
    ('Technology', 'Tech, digital, and innovation'),
    ('Sports', 'Football, athletics, and competition'),
    ('Lifestyle', 'Fashion, food, and everyday living'),
    ('Education', 'Learning, schools, and development'),
    ('Health', 'Wellness, medicine, and public health'),
    ('Opinion', 'Commentary, editorials, and perspectives'),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    for name, description in CATEGORIES:
        Category.objects.get_or_create(
            slug=slugify(name),
            defaults={'name': name, 'description': description}
        )


def publish_existing_posts(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogPost.objects.filter(status='draft').update(status='published')


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_tag_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_noop),
        migrations.RunPython(publish_existing_posts, reverse_noop),
    ]
