# Generated by Django 5.2.12 on 2026-04-02 19:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_seed_categories_and_publish_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=20000),
        ),
    ]
