# Generated by Django 5.2.12 on 2026-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_bookmark_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_plain',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
